const NS='http://www.w3.org/2000/svg';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const svg=$('#plot'), W=700,H=520,cx=W/2,cy=H/2,scale=58;
const C={blue:'#4169e1',purple:'#7559d9',orange:'#ec8d42',green:'#1f9d75',red:'#dd5565',gray:'#98a2b3',ink:'#172033'};
let view='pca',step=0,playing=false,timer=null,drag=null;
let pca={points:[],center:true,standardize:false};
let svd={a:1.25,b:.75,c:.45,d:1.45,object:'circle'};
let qr={a1:[2.7,1.4],a2:[1.2,2.8],method:'gram'};

const configs={
 pca:{title:'Find the directions that matter.',copy:'Move the data. Then watch PCA center it, measure its spread, and discover its principal axes.',tag:'CORE IDEA',concept:'PCA rotates your coordinate system so the first axis captures as much variation as possible.',control:'Shape the data',canvas:'LIVE DATA SPACE',hint:'Drag points to reshape the dataset',progress:'PCA walkthrough',steps:['Data','Center','Covariance','Directions','Project','Explain']},
 svd:{title:'Take a matrix apart — geometrically.',copy:'Change any matrix. Watch it rotate, stretch, and rotate again while its singular values reveal the true scale of the transformation.',tag:'THE FACTORIZATION',concept:'Every matrix transformation can be understood as an input rotation, axis-aligned scaling, and an output rotation.',control:'Build a matrix',canvas:'TRANSFORMATION SPACE',hint:'Edit the matrix or choose a preset',progress:'SVD walkthrough',steps:['Input','Vᵀ','Σ','U','Together','Rank']},
 qr:{title:'Build straight axes from tilted vectors.',copy:'Drag two vectors and watch Gram–Schmidt remove overlap, create an orthonormal basis, and record the coordinates in R.',tag:'THE FACTORIZATION',concept:'QR separates a matrix into orthonormal directions Q and the coefficients R needed to rebuild its columns.',control:'Set the columns',canvas:'VECTOR SPACE',hint:'Drag the arrow tips to change the columns',progress:'QR walkthrough',steps:['Columns','Normalize','Project','Subtract','Normalize','Rebuild']}
};
const lessons={
 pca:[
  ['ORIGINAL DATA','Start with the point cloud','Each dot is one observation with two measured features. Drag any point and every calculation updates instantly.','X = {x₁, x₂, …, xₙ}','The cloud has a visible direction. PCA will find it without being given an angle.'],
  ['CENTER THE DATA','Move the mean to zero','PCA first subtracts the feature-wise mean. This changes the location, but not the shape or relationships in the cloud.','Xᶜ = X − μ','After centering, the red mean marker sits exactly at the origin.'],
  ['MEASURE THE SPREAD','Build the covariance matrix','Covariance measures how the two features vary together. Large off-diagonal values mean their movement is related.','C = (Xᶜ)ᵀXᶜ / (n − 1)','The covariance matrix summarizes the entire cloud with just four values.'],
  ['FIND PRINCIPAL AXES','Choose the widest direction','The eigenvector with the largest eigenvalue becomes PC1. The perpendicular eigenvector becomes PC2.','C vᵢ = λᵢ vᵢ','PC1 follows the longest spread; PC2 captures the remaining perpendicular spread.'],
  ['PROJECT THE DATA','Express points on PC1','Projecting onto PC1 keeps the coordinate in the most informative direction and discards the other one.','zᵢ = v₁ᵀ(xᵢ − μ)','The gray segments show exactly what information is removed in a one-dimensional representation.'],
  ['EXPLAINED VARIANCE','Measure what was preserved','The eigenvalues equal variance along each principal axis. Their proportions tell us how much information each component retains.','ratioᵢ = λᵢ / Σλ','When PC1 explains most variance, a 2D dataset can be summarized well with just one number per point.']
 ],
 svd:[
  ['STARTING SHAPE','Begin with the unit circle','A circle contains every unit direction. Its transformation reveals how the matrix acts on all directions at once.','A = U Σ Vᵀ','A matrix sends the unit circle to an ellipse—or collapses it when rank is lost.'],
  ['INPUT ROTATION','Apply Vᵀ first','The right singular vectors choose special input directions. Vᵀ rotates or reflects those directions onto the coordinate axes.','x₁ = Vᵀx','These are the input directions that the matrix stretches without mixing.'],
  ['AXIS SCALING','Stretch with Σ','The diagonal matrix Σ scales the two special directions by the singular values σ₁ and σ₂.','x₂ = Σx₁','The singular values are always nonnegative and become the ellipse’s semiaxis lengths.'],
  ['OUTPUT ROTATION','Finish with U','U rotates or reflects the scaled ellipse into its final output orientation. Its columns are the left singular vectors.','Ax = Ux₂','U changes orientation, not length. The stretching already happened inside Σ.'],
  ['THE FULL PRODUCT','Reassemble the matrix','Performing Vᵀ, then Σ, then U gives exactly the same result as applying A in one step.','A = U Σ Vᵀ','The decomposition turns one complicated action into three simple geometric actions.'],
  ['RANK & APPROXIMATION','Keep the important direction','Each nonzero singular value contributes one rank-one layer. Keeping only σ₁ gives the best rank-one approximation.','A₁ = σ₁u₁v₁ᵀ','A tiny σ₂ means almost all of the matrix’s action lies along one input-output direction pair.']
 ],
 qr:[
  ['MATRIX COLUMNS','Treat columns as vectors','The columns of A may point in any directions. QR will replace them with perpendicular unit vectors spanning the same space.','A = [ a₁  a₂ ]','The original vectors can overlap; an orthonormal basis cannot.'],
  ['FIRST BASIS VECTOR','Normalize the first column','The first orthonormal direction keeps a₁’s direction but changes its length to one.','q₁ = a₁ / ‖a₁‖','The removed length is stored as r₁₁ in R.'],
  ['MEASURE THE OVERLAP','Project a₂ onto q₁','The dot product tells us how much of the second column points along the first basis direction.','proj = (q₁ᵀa₂)q₁','This parallel piece must be removed before a perpendicular direction can emerge.'],
  ['REMOVE THE OVERLAP','Create an orthogonal remainder','Subtracting the projection leaves a vector that is perpendicular to q₁.','u₂ = a₂ − (q₁ᵀa₂)q₁','The right-angle marker verifies that the overlap is gone.'],
  ['SECOND BASIS VECTOR','Normalize the remainder','Dividing u₂ by its length produces the second unit basis vector q₂.','q₂ = u₂ / ‖u₂‖','Q now has orthonormal columns, so QᵀQ equals the identity matrix.'],
  ['REBUILD THE MATRIX','Store coordinates in R','R records how much of every q direction is needed to reconstruct each original column.','A = QR','Q supplies the directions. R supplies the coordinates and lengths. Together they recover A exactly.']
 ]
};

function el(name,attrs={},parent=svg){const n=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));parent.appendChild(n);return n}
function line(x1,y1,x2,y2,cls='',stroke){return el('line',{x1,y1,x2,y2,class:cls,...(stroke?{stroke}:{})})}
function text(x,y,s,cls='svg-label'){const n=el('text',{x,y,class:cls});n.textContent=s;return n}
function pt([x,y]){return[cx+x*scale,cy-y*scale]}
function inv(x,y){return[(x-cx)/scale,(cy-y)/scale]}
function grid(){svg.innerHTML='';for(let x=2;x<W;x+=58)line(x,0,x,H,'grid-line');for(let y=28;y<H;y+=58)line(0,y,W,y,'grid-line');line(0,cy,W,cy,'axis');line(cx,0,cx,H,'axis');text(W-24,cy-8,'x');text(cx+8,15,'y')}
function arrow(v,color,label,width=3){const [x,y]=pt(v);line(cx,cy,x,y,'',color).setAttribute('stroke-width',width);const ang=Math.atan2(y-cy,x-cx),s=10;el('path',{d:`M ${x} ${y} L ${x-s*Math.cos(ang-.45)} ${y-s*Math.sin(ang-.45)} L ${x-s*Math.cos(ang+.45)} ${y-s*Math.sin(ang+.45)} Z`,fill:color});text(x+8,y-7,label,'svg-math')}
function matVec(A,v){return[A[0]*v[0]+A[1]*v[1],A[2]*v[0]+A[3]*v[1]]}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]} function norm(a){return Math.hypot(...a)} function mul(a,s){return[a[0]*s,a[1]*s]} function sub(a,b){return[a[0]-b[0],a[1]-b[1]]}
function fmt(n){return(Math.abs(n)<.0005?0:n).toFixed(2)}
function matrixHTML(vals){return `<div class="mini-matrix">[ ${vals.map(fmt).join('   ')} ]</div>`}
function covariance(){let pts=pca.points,mx=pts.reduce((s,p)=>s+p[0],0)/pts.length,my=pts.reduce((s,p)=>s+p[1],0)/pts.length;let xx=0,xy=0,yy=0;pts.forEach(p=>{let x=p[0]-mx,y=p[1]-my;xx+=x*x;xy+=x*y;yy+=y*y});let d=pts.length-1;xx/=d;xy/=d;yy/=d;if(pca.standardize){let den=Math.sqrt(xx*yy)||1;xy/=den;xx=yy=1}let tr=xx+yy,disc=Math.sqrt((xx-yy)**2+4*xy**2),l1=(tr+disc)/2,l2=(tr-disc)/2;let v1=Math.abs(xy)>.00001?[xy,l1-xx]:(xx>=yy?[1,0]:[0,1]);let nv=norm(v1)||1;v1=mul(v1,1/nv);if(v1[0]<0)v1=mul(v1,-1);return{mx,my,xx,xy,yy,l1,l2,v1,v2:[-v1[1],v1[0]]}}
function initPoints(kind='line'){const out=[];let n=18;for(let i=0;i<n;i++){let t=(i-(n-1)/2)/3.7,j=Math.sin(i*12.989)*.44;if(kind==='negative')out.push([t,-.75*t+j]);else if(kind==='circle'){let a=i/n*Math.PI*2,r=2.1+.25*Math.sin(i*4);out.push([r*Math.cos(a),r*Math.sin(a)])}else if(kind==='clusters')out.push([i<9?-1.5:1.5,(i<9?-1:1)+j*1.5+((i%5)-2)*.18]);else if(kind==='wide')out.push([t*1.25,.25*t+j*1.4]);else out.push([t,.72*t+j])}pca.points=out}

function setControlHTML(){const c=$('#controls');if(view==='pca')c.innerHTML=`<div class="control-group"><label>Dataset presets</label><div class="preset-grid">${[['line','Correlated'],['negative','Negative'],['wide','Noisy'],['circle','Circular'],['clusters','Clusters']].map(([k,n])=>`<button class="preset" data-preset="${k}">${n}</button>`).join('')}</div></div><div class="control-group"><label>Rotation <output id="rotateOut">0°</output></label><input id="rotate" type="range" min="-90" max="90" value="0"></div><div class="control-group"><label>Noise <output id="noiseOut">0%</output></label><input id="noise" type="range" min="0" max="100" value="0"></div><div class="toggle-row"><span>Center the data</span><button class="switch on" id="centerToggle" aria-label="Toggle centering"></button></div><div class="toggle-row"><span>Standardize features</span><button class="switch" id="stdToggle" aria-label="Toggle standardization"></button></div>`;
 if(view==='svd')c.innerHTML=`<label class="matrix-label">Transformation matrix A</label><div class="matrix-grid">${['a','b','c','d'].map(k=>`<input type="number" step="0.1" id="m_${k}" value="${svd[k]}">`).join('')}</div><div class="control-group"><label>Matrix presets</label><div class="preset-grid">${[['stretch','Stretch'],['rotate','Rotate'],['shear','Shear'],['reflect','Reflect'],['rank1','Rank 1'],['project','Project']].map(([k,n])=>`<button class="preset" data-preset="${k}">${n}</button>`).join('')}</div></div><div class="control-group"><label>Visual object</label><div class="preset-grid">${[['circle','Circle + grid'],['square','Square'],['vectors','Vectors']].map(([k,n])=>`<button class="preset object ${svd.object===k?'active':''}" data-object="${k}">${n}</button>`).join('')}</div></div><div class="toggle-row"><span>Show singular vectors</span><button class="switch on" id="vectorToggle"></button></div>`;
 if(view==='qr')c.innerHTML=`<label class="matrix-label">Matrix columns</label><div class="matrix-grid">${[['q_a1x',qr.a1[0]],['q_a2x',qr.a2[0]],['q_a1y',qr.a1[1]],['q_a2y',qr.a2[1]]].map(([k,v])=>`<input type="number" step="0.1" id="${k}" value="${v}">`).join('')}</div><div class="control-group"><label>Vector presets</label><div class="preset-grid">${[['general','General'],['orthogonal','Already ⟂'],['parallel','Parallel'],['nearly','Nearly parallel']].map(([k,n])=>`<button class="preset" data-preset="${k}">${n}</button>`).join('')}</div></div><div class="control-group"><label>Method</label><div class="preset-grid"><button class="preset active">Gram–Schmidt</button><button class="preset" title="Householder reflection concept is explained in the note below">Householder</button></div></div><div class="toggle-row"><span>Show right angle</span><button class="switch on" id="angleToggle"></button></div>`;
 bindControls();
}
function bindControls(){
 $$('.preset[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
 if(view==='pca'){$('#rotate').oninput=e=>{let a=+e.target.value*Math.PI/180,$o=$('#rotateOut');$o.value=e.target.value+'°';pca.points=pca.points.map(([x,y])=>[x*Math.cos(a/90)-y*Math.sin(a/90),x*Math.sin(a/90)+y*Math.cos(a/90)]);e.target.value=0;render()};$('#noise').oninput=e=>{$('#noiseOut').value=e.target.value+'%';let n=+e.target.value/800;pca.points=pca.points.map((p,i)=>[p[0],p[1]+Math.sin(i*17.13+e.target.value)*n]);render()};$('#centerToggle').onclick=e=>{pca.center=!pca.center;e.target.classList.toggle('on',pca.center);render()};$('#stdToggle').onclick=e=>{pca.standardize=!pca.standardize;e.target.classList.toggle('on',pca.standardize);render()}}
 if(view==='svd'){['a','b','c','d'].forEach(k=>$('#m_'+k).oninput=e=>{svd[k]=+e.target.value||0;render()});$$('[data-object]').forEach(b=>b.onclick=()=>{svd.object=b.dataset.object;$$('[data-object]').forEach(x=>x.classList.toggle('active',x===b));render()})}
 if(view==='qr'){const map={q_a1x:[0,0],q_a1y:[0,1],q_a2x:[1,0],q_a2y:[1,1]};Object.entries(map).forEach(([id,[v,i]])=>$('#'+id).oninput=e=>{(v?qr.a2:qr.a1)[i]=+e.target.value||0;render()})}
}
function applyPreset(k){if(view==='pca')initPoints(k);if(view==='svd'){let m={stretch:[2,0,0,.65],rotate:[.71,-.71,.71,.71],shear:[1,1.1,0,1],reflect:[1,0,0,-1],rank1:[1.5,.75,1,.5],project:[1,0,0,0]}[k];[svd.a,svd.b,svd.c,svd.d]=m;setControlHTML()}if(view==='qr'){let m={general:[[2.7,1.4],[1.2,2.8]],orthogonal:[[2.5,1.5],[-1.5,2.5]],parallel:[[2.5,1.3],[3.7,1.92]],nearly:[[2.7,1.4],[3.5,1.95]]}[k];qr.a1=m[0];qr.a2=m[1];setControlHTML()}step=0;render()}

function renderPCA(){grid();let s=covariance(),ox=step>=1&&pca.center?s.mx:0,oy=step>=1&&pca.center?s.my:0;let shown=pca.points.map(p=>[p[0]-ox,p[1]-oy]);if(step>=3){let len=5.5;line(...pt(mul(s.v1,-len)),...pt(mul(s.v1,len)),'pc1');line(...pt(mul(s.v2,-len)),...pt(mul(s.v2,len)),'pc2');text(...pt(mul(s.v1,3.9)),'PC1','svg-math');text(...pt(mul(s.v2,3.3)),'PC2','svg-math')}
 if(step===2){let angle=Math.atan2(s.v1[1],s.v1[0]);for(let i=-3;i<=3;i++){let a=angle+i*.17,v=[Math.cos(a)*4.5,Math.sin(a)*4.5];line(...pt(mul(v,-1)),...pt(v),'candidate');}}
 if(step>=4)shown.forEach(p=>{let z=dot(p,s.v1),q=mul(s.v1,z);line(...pt(p),...pt(q),'projection')});
 shown.forEach((p,i)=>{let pos=step>=4?mul(s.v1,dot(p,s.v1)):p,[x,y]=pt(pos);let n=el('circle',{cx:x,cy:y,r:6,class:'point','data-i':i,tabindex:0});n.addEventListener('pointerdown',e=>{if(step>=4)return;drag=i;n.setPointerCapture(e.pointerId)})});
 if(step>=1){let [x,y]=pt([0,0]);el('circle',{cx:x,cy:y,r:8,class:'mean-point'});text(x+12,y-10,'mean','svg-label')}
 svg.onpointermove=e=>{if(drag===null||step>=4)return;let r=svg.getBoundingClientRect(),[x,y]=inv((e.clientX-r.left)*W/r.width,(e.clientY-r.top)*H/r.height);let s=covariance();pca.points[drag]=[x+(step>=1?s.mx:0),y+(step>=1?s.my:0)];render()};svg.onpointerup=()=>drag=null;
 let ratio=s.l1/(s.l1+s.l2||1)*100;$('#metrics').innerHTML=`<div class="metric"><span>MEAN</span><b>(${fmt(s.mx)}, ${fmt(s.my)})</b></div><div class="metric"><span>PC1 VARIANCE</span><b>${fmt(s.l1)}</b></div><div class="metric"><span>PC2 VARIANCE</span><b>${fmt(s.l2)}</b></div><div class="metric"><span>PC1 EXPLAINS</span><b>${fmt(ratio)}%</b></div>`;if(step===2)$('#equation').innerHTML=`C = [ ${fmt(s.xx)}  ${fmt(s.xy)} ; ${fmt(s.xy)}  ${fmt(s.yy)} ]`;if(step>=3)$('#equation').innerHTML=`v₁ = (${fmt(s.v1[0])}, ${fmt(s.v1[1])})`;
 $('#legend').innerHTML=`<span><i style="background:${C.blue}"></i>Data</span>${step>=3?`<span><i style="background:${C.purple}"></i>PC1</span><span><i style="background:${C.orange}"></i>PC2</span>`:''}`
}
function svdCalc(){let {a,b,c,d}=svd;let x=a*a+c*c,y=a*b+c*d,z=b*b+d*d,tr=x+z,disc=Math.sqrt((x-z)**2+4*y*y),l1=Math.max(0,(tr+disc)/2),l2=Math.max(0,(tr-disc)/2),s1=Math.sqrt(l1),s2=Math.sqrt(l2);let v1=Math.abs(y)>.000001?[y,l1-x]:(x>=z?[1,0]:[0,1]);v1=mul(v1,1/(norm(v1)||1));if(v1[0]<0)v1=mul(v1,-1);let v2=[-v1[1],v1[0]],u1=s1>1e-6?mul(matVec([a,b,c,d],v1),1/s1):[1,0],u2=s2>1e-6?mul(matVec([a,b,c,d],v2),1/s2):[-u1[1],u1[0]];return{A:[a,b,c,d],s1,s2,v1,v2,u1,u2,det:a*d-b*c}}
function drawShape(A,cls){let pts=[];if(svd.object==='square')pts=[[-1,-1],[1,-1],[1,1],[-1,1],[-1,-1]];else if(svd.object==='vectors'){arrow(matVec(A,[1.7,.4]),C.purple,'');arrow(matVec(A,[-.5,1.5]),C.orange,'');return}else for(let i=0;i<=100;i++){let t=i/100*Math.PI*2;pts.push([Math.cos(t),Math.sin(t)])}let d=pts.map((p,i)=>{let [x,y]=pt(matVec(A,p));return`${i?'L':'M'}${x},${y}`}).join(' ');el('path',{d,class:cls})}
function drawGridTransform(A){for(let i=-3;i<=3;i++){let p1=pt(matVec(A,[i,-3])),p2=pt(matVec(A,[i,3]));line(...p1,...p2,'', '#e4e8ef');p1=pt(matVec(A,[-3,i]));p2=pt(matVec(A,[3,i]));line(...p1,...p2,'','#e4e8ef')}}
function renderSVD(){grid();let s=svdCalc(),Vt=[s.v1[0],s.v1[1],s.v2[0],s.v2[1]],Sig=[s.s1,0,0,s.s2],U=[s.u1[0],s.u2[0],s.u1[1],s.u2[1]],T=[1,0,0,1];if(step===1)T=Vt;if(step===2)T=Sig;if(step===3)T=U;if(step>=4)T=s.A;drawGridTransform(T);drawShape([1,0,0,1],'shape-original');drawShape(T,'shape-stage');if(step>=1){arrow(step<3?s.v1:s.u1,C.purple,step<3?'v₁':'u₁');arrow(step<3?s.v2:s.u2,C.orange,step<3?'v₂':'u₂')}let rank=(s.s1>1e-6?1:0)+(s.s2>1e-6?1:0),cond=s.s2>1e-6?s.s1/s.s2:Infinity;$('#metrics').innerHTML=`<div class="metric"><span>σ₁</span><b>${fmt(s.s1)}</b></div><div class="metric"><span>σ₂</span><b>${fmt(s.s2)}</b></div><div class="metric"><span>RANK</span><b>${rank}</b></div><div class="metric"><span>CONDITION</span><b>${isFinite(cond)?fmt(cond):'∞'}</b></div>`;if(step===1)$('#equation').innerHTML=`Vᵀ = [ ${Vt.map(fmt).join('  ')} ]`;if(step===2)$('#equation').innerHTML=`Σ = diag(${fmt(s.s1)}, ${fmt(s.s2)})`;if(step===3)$('#equation').innerHTML=`U = [ ${U.map(fmt).join('  ')} ]`;if(step>=4)$('#equation').innerHTML=`A = U Σ Vᵀ`;$('#legend').innerHTML=`<span><i style="background:${C.blue}"></i>Original</span><span><i style="background:${C.purple}"></i>Current stage</span>`}
function qrCalc(){let n1=norm(qr.a1),q1=n1>1e-8?mul(qr.a1,1/n1):[1,0],r12=dot(q1,qr.a2),proj=mul(q1,r12),u2=sub(qr.a2,proj),n2=norm(u2),q2=n2>1e-8?mul(u2,1/n2):[-q1[1],q1[0]];return{q1,q2,proj,u2,r11:n1,r12,r22:n2}}
function draggableArrow(v,color,label,id){arrow(v,color,label,3);let [x,y]=pt(v),n=el('circle',{cx:x,cy:y,r:9,fill:'#fff',stroke:color,'stroke-width':3,class:'drag-tip','data-id':id});n.style.cursor='grab';n.onpointerdown=e=>{drag=id;n.setPointerCapture(e.pointerId)}}
function renderQR(){grid();let q=qrCalc();draggableArrow(qr.a1,C.blue,'a₁','a1');draggableArrow(qr.a2,C.orange,'a₂','a2');if(step>=1)arrow(mul(q.q1,2.2),C.purple,'q₁');if(step>=2){arrow(q.proj,C.gray,'proj');line(...pt(qr.a2),...pt(q.proj),'qr-proj')}if(step>=3)arrow(q.u2,C.green,'u₂');if(step>=4)arrow(mul(q.q2,2.2),C.green,'q₂');if(step>=5){let p=pt(q.q1),r=pt(q.q2);line(...p,...r,'projection')}
 svg.onpointermove=e=>{if(!drag)return;let r=svg.getBoundingClientRect(),v=inv((e.clientX-r.left)*W/r.width,(e.clientY-r.top)*H/r.height);qr[drag]=v;setControlValuesQR();render()};svg.onpointerup=()=>drag=null;
 let orth=Math.abs(dot(q.q1,q.q2));$('#metrics').innerHTML=`<div class="metric"><span>r₁₁ = ‖a₁‖</span><b>${fmt(q.r11)}</b></div><div class="metric"><span>r₁₂ = q₁ᵀa₂</span><b>${fmt(q.r12)}</b></div><div class="metric"><span>r₂₂ = ‖u₂‖</span><b>${fmt(q.r22)}</b></div><div class="metric"><span>|q₁ᵀq₂|</span><b>${fmt(orth)}</b></div>`;if(step>=4)$('#equation').innerHTML=`Q = [ ${[q.q1[0],q.q2[0],q.q1[1],q.q2[1]].map(fmt).join('  ')} ]`;if(step>=5)$('#equation').innerHTML=`R = [ ${fmt(q.r11)}  ${fmt(q.r12)} ; 0  ${fmt(q.r22)} ]`;$('#legend').innerHTML=`<span><i style="background:${C.blue}"></i>a₁</span><span><i style="background:${C.orange}"></i>a₂</span>${step>=1?`<span><i style="background:${C.purple}"></i>Basis</span>`:''}`}
function setControlValuesQR(){let ids={q_a1x:qr.a1[0],q_a1y:qr.a1[1],q_a2x:qr.a2[0],q_a2y:qr.a2[1]};Object.entries(ids).forEach(([k,v])=>{let e=$('#'+k);if(e)e.value=fmt(v)})}

function updateLesson(){let l=lessons[view][step],cfg=configs[view];$('#lessonKicker').textContent=`STEP ${step+1} · ${l[0]}`;$('#lessonTitle').textContent=l[1];$('#lessonBody').textContent=l[2];$('#equation').textContent=l[3];$('#insightText').textContent=l[4];$('#stepCount').textContent=`${step+1} / ${cfg.steps.length}`;$('#timelineFill').style.width=`${step/(cfg.steps.length-1)*100}%`;$('#stepPills').innerHTML=cfg.steps.map((n,i)=>`<span class="step-pill ${i<step?'done':i===step?'current':''}"><i>${i<step?'✓':i+1}</i>${n}</span>`).join('')}
function render(){updateLesson();if(view==='pca')renderPCA();if(view==='svd')renderSVD();if(view==='qr')renderQR()}
function switchView(v){view=v;step=0;pause();let c=configs[v];$('#heroTitle').textContent=c.title;$('#heroCopy').textContent=c.copy;$('#conceptTag').textContent=c.tag;$('#conceptText').textContent=c.concept;$('#controlTitle').textContent=c.control;$('#canvasLabel').textContent=c.canvas;$('#plotHint').textContent=c.hint;$('#progressTitle').textContent=c.progress;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));setControlHTML();render()}
function pause(){playing=false;clearInterval(timer);$('#playIcon').textContent='▶';$('#playText').textContent='Play walkthrough'}
function play(){if(playing){pause();return}playing=true;$('#playIcon').textContent='Ⅱ';$('#playText').textContent='Pause';timer=setInterval(()=>{if(step>=5){pause();return}step++;render()},1500)}
$$('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#resetBtn').onclick=()=>{if(view==='pca')initPoints();if(view==='svd')svd={a:1.25,b:.75,c:.45,d:1.45,object:'circle'};if(view==='qr')qr={a1:[2.7,1.4],a2:[1.2,2.8],method:'gram'};step=0;setControlHTML();render()};$('#prevBtn').onclick=()=>{step=Math.max(0,step-1);pause();render()};$('#nextBtn').onclick=()=>{step=Math.min(5,step+1);pause();render()};$('#playBtn').onclick=play;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();play()}if(e.key==='ArrowRight')$('#nextBtn').click();if(e.key==='ArrowLeft')$('#prevBtn').click()});
const modal=$('#modal');$('#learnBtn').onclick=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')};function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#modalClose').onclick=closeModal;$('#modalStart').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
initPoints();switchView('pca');
